### ISSUE TITLE
Website mockups

### ISSUE THREAD

**Issue by ShauryaBhandari** [sanscript-tech/orphan_support-php#12]
Mockups need to be made for the project so that the front-end devs can directly start working on them. 
Need some professional UI/UX designers for this issue. 
The best design will be used and implemented. 
#9 Can be tracked for inputs given by people. 
**All the best!**

**Comment by Harshita248** [comment]
**Illustrations relevant to the website are also welcomed.**

**Comment by saloniankita** [comment]
Can I and my teammate @bhanvimenghani work on this issue together ?

**Comment by Harshita248** [comment]
yes you can but you both have to put the screenshots here too @saloniankita @bhanvimenghani

**Comment by Harshita248** [comment]
@saloniankita and @bhanvimenghani please work faster or else will assign the issue to someone else

**Comment by saloniankita** [comment]
We are working on this issue @Harshita248 . We'll be adding the screenshots soon.

**Comment by saloniankita** [comment]
These are some of the illustrations that I came up with, that aligns with the **theme of the project**.
Kindly have a look at these.
![Design-1](https://user-images.githubusercontent.com/56873389/97110353-ba6ad580-16fe-11eb-82bc-a7d05bcc6bd9.png)

![Design-2](https://user-images.githubusercontent.com/56873389/97110352-b9d23f00-16fe-11eb-977f-20ed6678f8fb.png)

![Design-3](https://user-images.githubusercontent.com/56873389/97110350-b9d23f00-16fe-11eb-804c-aa7bfeeb6f32.png)

![Design-4](https://user-images.githubusercontent.com/56873389/97110349-b939a880-16fe-11eb-906b-424ea4dabc83.png)

![Design-5](https://user-images.githubusercontent.com/56873389/97110347-b76fe500-16fe-11eb-9dfa-f77f6219593d.png)

**Comment by Surajbokde** [comment]
@Harshita248 is this issue is over??

**Comment by Harshita248** [comment]
Yes
