### ISSUE TITLE
Colour scheme and fonts

### ISSUE THREAD

**Issue by ShauryaBhandari** [sanscript-tech/orphan_support-php#13]
Ideas regarding the best colour scheme (light and dark) and the best suited font for this. 
Submit your ideas below and the best one will be used. 
**All the best!**

**Comment by punitsakre23** [comment]
Hi, I'll do this.

**Comment by Harshita248** [comment]
@punitsakre23 please comment your ideas and when decided we can move with it : )

**Comment by punitsakre23** [comment]
![Fifth](https://user-images.githubusercontent.com/66567141/96540806-3b1f7100-12bc-11eb-93b5-cc88b67ccd2f.png)
![First](https://user-images.githubusercontent.com/66567141/96540810-3c509e00-12bc-11eb-8955-fa1577a6824b.png)
![Fourth](https://user-images.githubusercontent.com/66567141/96540814-3d81cb00-12bc-11eb-81f3-b7ca4386ed97.png)
![Second](https://user-images.githubusercontent.com/66567141/96540815-3d81cb00-12bc-11eb-8c50-8ccdef1aa2ef.png)
![Third](https://user-images.githubusercontent.com/66567141/96540817-3e1a6180-12bc-11eb-9034-4feb9480d0ee.png)

**Comment by punitsakre23** [comment]
I tried, plz let me know if I need to change something or any other shades.

**Comment by ShauryaBhandari** [comment]
Nice job @punitsakre23 ! Looks really good.

**Comment by ShauryaBhandari** [comment]
@Harshita248 Please approve.

**Comment by Harshita248** [comment]
yes its good . Lets go with second or third one @punitsakre23

**Comment by punitsakre23** [comment]
Thankyou @ShauryaBhandari  and @Harshita248

**Comment by punitsakre23** [comment]
Do I need to send a pull request with snip or do something else?

**Comment by sejalshri** [comment]
@Harshita248 @ShauryaBhandari Can i add custom scrollbar according to the color theme ?

**Comment by ShauryaBhandari** [comment]
Yes please do. But don't make it too colourful/shiny. Keep it plain and subtle, but add one.

**Comment by punitsakre23** [comment]
![Font1](https://user-images.githubusercontent.com/66567141/96697298-5fa54700-13a9-11eb-96c6-23cd3d59b024.png)
![Font2](https://user-images.githubusercontent.com/66567141/96697305-616f0a80-13a9-11eb-884d-1bde434b5614.png)
![Font3](https://user-images.githubusercontent.com/66567141/96697307-62a03780-13a9-11eb-8b08-df936425131b.png)
![Font4](https://user-images.githubusercontent.com/66567141/96697313-63d16480-13a9-11eb-86aa-9f3a053d46dd.png)

**Comment by punitsakre23** [comment]
Are the fonts good or require some changes. @ShauryaBhandari @Harshita248

**Comment by punitsakre23** [comment]
??? Correct me if I got it wrong.

**Comment by Harshita248** [comment]
keep the third one for the font style @punitsakre23

**Comment by Harshita248** [comment]
All good
