### ISSUE TITLE
Improve contributing.md

### ISSUE THREAD

**Issue by chehak123** [sanscript-tech/orphan_support-php#14]
Organize various steps to contribute to the project and add screenshots/images to make it attractive and interesting.

**Comment by shivangisinghal0304** [comment]
Can i work on it?

**Comment by shivang-garg** [comment]
Can i work on it?

**Comment by bhavesh1129** [comment]
May I work on it?

**Comment by Harshita248** [comment]
Go ahead @shivangisinghal0304 as its first come first serve basis and we do not require more than one person @bhavesh1129

**Comment by Harshita248** [comment]
@shivangisinghal0304 please complete this asap by tomorrow otherwise it will be assigned to someone else

**Comment by Harshita248** [comment]
@bhavesh1129 go ahead as I cannot see any progress by @shivangisinghal0304 so now @bhavesh1129 work on this issue please and  try to complete it asap
