### ISSUE TITLE
Website Footer.

### ISSUE THREAD

**Issue by tanayduggad0299** [sanscript-tech/orphan_support-php#23]
Can I work on this along with my team?

**Comment by Tejas1510** [comment]
I would love to work on this issue

**Comment by chehak123** [comment]
@tanayduggad0299 you can go ahead with it. Do propose your ideas along with screenshots.

**Comment by chehak123** [comment]
@Tejas1510 due to first come first served basis, this issue is currently assigned to @tanayduggad0299. It would be assigned to you later if some help would be needed.

**Comment by Tejas1510** [comment]
Sure Sir
Thanks for response

**Comment by tanayduggad0299** [comment]
Thanks for assignment!!

**Comment by Harshita248** [comment]
Design the footer according to the template , do it fast

**Comment by tanayduggad0299** [comment]
Sure, I will submit this soon.

**Comment by chehak123** [comment]
Do add the screenshots.
