### ISSUE TITLE
The Project is missing required Documentation

### ISSUE THREAD

**Issue by Git-Harshit** [sanscript-tech/orphan_support-php#3]
The Repository has just a README file for documentation, and that is empty as well with nothing more than a Project Heading (which is same as the repository content). Moreover, additional documents such as Contributing, Code of Conduct, and any other are missing for the repository. Including these items in here will allow new users to be able to join in and will facilitate them in understanding the motive of the repository and let them contribute and collaborate here.

It'd be great if these files are included here soon, since the contributing to the repos has already started under Autumn of Open Source by Sanscript Tech! 😉

**Comment by Git-Harshit** [comment]
@swarupbhanjachowdhury Please add any relevant labels to it, then allow me to work on this, and let me add at least some of the content for you to review and others to add upon later.

**Comment by Harshita248** [comment]
@Git-Harshit go ahead and add the above files for a clear understanding. Thank you for help : )
