### ISSUE TITLE
Creating a database table structure for storing data of children

### ISSUE THREAD

**Issue by ujwal111** [sanscript-tech/orphan_support-php#30]
Creation of database table where the information of all the children are available/accessed, Can I work on this issue?

**Comment by SanjeebNath382** [comment]
Hey can I work on this?

**Comment by Harshita248** [comment]
Go ahead @ujwal111 and if you want any help @SanjeebNath382 can help you out with it

**Comment by ujwal111** [comment]
Thank you for the assignment, I will surely take the help of @SanjeebNath382 if I ever get stuck in the middle

**Comment by SanjeebNath382** [comment]
Sure @ujwal111 👍
