### ISSUE TITLE
organize the navbar with menu options and login and register buttons

### ISSUE THREAD

**Issue by Harshita248** [sanscript-tech/orphan_support-php#35]
Navbar should include logo, home page, about, blog, causes, contact us pages with donate now ,login and register buttons on the right. Remove the rest . Also remove the details from the top like follow us, call and email details as we will include that in the footer.

**Comment by Himanshi2016** [comment]
I would love to work on this issue. Only documentation right ?

**Comment by Harshita248** [comment]
Yes @Himanshi2016 go ahead

**Comment by punitsakre23** [comment]
I would like to work on this.

**Comment by pallavithakare28** [comment]
@Harshita248 May I work on this issue?

**Comment by Harshita248** [comment]
@pallavithakare28  it's already been assigned to someone as you can check and it's an easy issue so one person is enough for this. There are many more issues listed you can pick them accordingly : )

**Comment by Harshita248** [comment]
done
