### ISSUE TITLE
Organize the homepage with relevant illustrations at different places and remove certain sections

### ISSUE THREAD

**Issue by Harshita248** [sanscript-tech/orphan_support-php#36]
Remove volunteer sections, events as well as article sections and make the homepage look good by adding latest css styling.

**Comment by m-code12** [comment]
I would like to take this up @Harshita248

**Comment by steveoo-tech** [comment]
I would love the opportunity to take this challenge! It would be my first contribution ever and I'm excited

**Comment by Harshita248** [comment]
Go ahead @m-code12  if you are a participant under Autumn of Open Source 2020 then you can work on this issue.

**Comment by Harshita248** [comment]
@steveoo-tech  the issue is being assigned on first come first serve basis so possibly look for some unassigned ones.

**Comment by m-code12** [comment]
> Go ahead @m-code12 if you are a participant under Autumn of Open Source 2020 then you can work on this issue.

Yes I am
