### ISSUE TITLE
Add a login and signup page relevant to the website.

### ISSUE THREAD

**Issue by Harshita248** [sanscript-tech/orphan_support-php#37]
Also add illustrations and make it look good as needed.

**Comment by SanjeebNath382** [comment]
Hey can I take up this, I have to add the scripting as well right?

**Comment by Himanshi2016** [comment]
I would like to work on this issue.

**Comment by Harshita248** [comment]
@SanjeebNath382 go on with the priority of making both the pages relevant to the website yeah you can add validation and all required here. But for storing the details we have another issue listed so don't work on that here. We have separate issues and separate pr's will be accepted.

**Comment by Harshita248** [comment]
@Himanshi2016  if the work is not done within time constraint or can be enhanced then if needed I may assign this to you but not now.

**Comment by Himanshi2016** [comment]
Okay , Thanks

**Comment by chehak123** [comment]
@SanjeebNath382 do complete it by 6th november or it will be unassigned.

**Comment by SanjeebNath382** [comment]
I have made the PR and it has been merged

**Comment by chehak123** [comment]
okay great!!
