### ISSUE TITLE
Add relevant and catchy content in donate page. 

### ISSUE THREAD

**Issue by chehak123** [sanscript-tech/orphan_support-php#40]

**Comment by bhavesh1129** [comment]
May I work on this?

**Comment by sakshi300699** [comment]
Would like to work on this

**Comment by chehak123** [comment]
It is assigned to you @bhavesh1129 due to first come first served basis. @sakshi300699 look for some other unassigned issues.

**Comment by chehak123** [comment]
@bhavesh1129 Reduce the content for donate page and we'll keep the layout as it is.

**Comment by chehak123** [comment]
make seperate prs for all issues

**Comment by chehak123** [comment]
add the caption which I approved on home page header carousel and just add the content on the donate page and keep the layout as it is.
