### ISSUE TITLE
Suggest and add appropriate captions for home page header section.

### ISSUE THREAD

**Issue by chehak123** [sanscript-tech/orphan_support-php#41]

**Comment by bhavesh1129** [comment]
Hey! Can I take this issue and work on it?

**Comment by sakshi300699** [comment]
Would like to work on this

**Comment by chehak123** [comment]
@bhavesh1129 and @sakshi300699 both of you can give your suggestions here. Appropriate ones would be finalized.

**Comment by Surajbokde** [comment]
hey i would like to work.
`RAISE YOUR HELPING HANDS FOR POOR PEOPLE`
`Donate For The Orphanage Children`
we can use this as Caption .
with a background image .
Orphanage Support at header Not looking attractive ,instead we include that in nav bar.
after that our header section will start.
this header we may include in the home page only.

**Comment by punitsakre23** [comment]
I would like to work on this.

**Comment by sakshi300699** [comment]
Some Suggestions for caption for homepage :

-  Let's make miracle happen in someone's life, by giving them the gift of a family.

- To be someone's family doesn't require blood relation, the feeling of love and commitment is enough.

- The purest kind of service that one can do to mankind is gifting someone the privilege to love and be loved in a family.

- Orphanage Support : A place where family finds family

**Comment by chehak123** [comment]
@Harshita248 kindly finalize the captions for home page.

**Comment by Harshita248** [comment]
3rd and 4th caption included by @sakshi300699  is good .... Looking for your opinion @chehak123

**Comment by chehak123** [comment]
@sakshi300699 add 3,4th caption in header section in home page and make the pr

**Comment by chehak123** [comment]
@bhavesh1129 add second caption of the ones suggested by you in header section and make the pr

**Comment by sakshi300699** [comment]
Okay Ma'am!

**Comment by bhavesh1129** [comment]
Ok Ma'am!
