### ISSUE TITLE
Also work on showing the details of children which gets displayed following the about us section in that page.

### ISSUE THREAD

**Issue by Harshita248** [sanscript-tech/orphan_support-php#42]
fetched details of children in orphanages. must get displayed on the about us page

**Comment by sakshi300699** [comment]
I believe that here it's the front end, we need to work on, fetching the data (given in the children database, given in mock control flow) and displaying it on the page. Am I right?

**Comment by Harshita248** [comment]
Database is done just fetching and displaying of data on the page needs to be added.

**Comment by sakshi300699** [comment]
Okay ma'am, would like to work on this

**Comment by Harshita248** [comment]
Okay @sakshi300699  you can go ahead. In case of any problem ask in orphan support channel on slack.

**Comment by Harshita248** [comment]
done
