### ISSUE TITLE
Add payment integration gateway for donate page using PHP

### ISSUE THREAD

**Issue by chehak123** [sanscript-tech/orphan_support-php#43]

**Comment by pwilson77** [comment]
I will like to work on this issue @chehak123

**Comment by chehak123** [comment]
Go ahead @pwilson77

**Comment by chehak123** [comment]
@pwilson77 if you are a participant under Autumn of Open Source then you can work on it.

**Comment by pwilson77** [comment]
@chehak123 yes I am a participant I will start working on it

**Comment by chehak123** [comment]
Great!! you may go ahead

**Comment by chehak123** [comment]
@pwilson77 make it faster and complete it by 7th november

**Comment by pwilson77** [comment]
ok @chehak123  am already done about I just need to check some few things before creating the pull request

**Comment by Harshita248** [comment]
done
