### ISSUE TITLE
Create a report section where a person after registration can create a report about an old age person who is abandoned by the family.  

### ISSUE THREAD

**Issue by Harshita248** [sanscript-tech/orphan_support-php#44]
If a person finds a child or any elderly person abandoned by family ..one can create a report so that an email with the person's details and  also the details of one who is abandoned should be sent to nearby orphanages. **Also add age limit and occupation +salary of a person who is creating the report.**

**Comment by sravani-7701** [comment]
Could you please assign this to me

**Comment by Harshita248** [comment]
Yeah okay @sravani-7701

**Comment by chehak123** [comment]
@sravani-7701 do complete it by 6th november or it will be assigned to somebody else.

**Comment by Surajbokde** [comment]
@Harshita248 we are do this in contact us page so  i think no need of this

**Comment by Harshita248** [comment]
Okay
