### ISSUE TITLE
Suggest designs for photo gallery section in blog page

### ISSUE THREAD

**Issue by chehak123** [sanscript-tech/orphan_support-php#45]

**Comment by Akansha-Bhandari** [comment]
i would like to work on this issue..

**Comment by Surajbokde** [comment]
i would like to work on this issue

**Comment by chehak123** [comment]
@Akansha-Bhandari and @Surajbokde both of you can share your ideas here itself regarding photo gallery designs. Appropriate one will be chosen and will be assigned.

**Comment by Surajbokde** [comment]
@chehak123 should i post ss here

**Comment by chehak123** [comment]
yes you can

**Comment by Surajbokde** [comment]
![Capture1](https://user-images.githubusercontent.com/66197682/97795033-70668000-1c27-11eb-867d-1d793efcb67c.JPG)
![Capture](https://user-images.githubusercontent.com/66197682/97795038-7bb9ab80-1c27-11eb-85ee-f367ef7de7aa.JPG)
@chehak123  plz check .given images are both in dark and light theme

**Comment by chehak123** [comment]
These are blogpost cards template. I want suggestions for photo gallery.

**Comment by Surajbokde** [comment]
ok we can make a new blog-gallery page. 
![Capture4](https://user-images.githubusercontent.com/66197682/97797092-fb537480-1c3f-11eb-95b9-1c10c733e856.JPG)
![Capture3](https://user-images.githubusercontent.com/66197682/97797093-fd1d3800-1c3f-11eb-95df-17b2bb42cd61.JPG)
![Capture5](https://user-images.githubusercontent.com/66197682/97797094-fdb5ce80-1c3f-11eb-9df7-e4f088626401.JPG)

@chehak123  just have a look .
i just added extra padding between image ,we can remove that also if require.

**Comment by chehak123** [comment]
we don't need a full gallery page. we need just a section of photo gallery (a collage type) and we can add carousel to make it attractive.

**Comment by Surajbokde** [comment]
![image](https://user-images.githubusercontent.com/66197682/97862783-f1a73b00-1d2b-11eb-9626-ad43ee18e846.png)
 
i don't what exactly u want but we can make collage of this type .
we can do 2 things -
1.we can make collage images ready . and perform slideshow.
2. or we can make the section (as given in image)  of this and apply effect on it so that image get change after every 2 sec. this will look amazing.

@chehak123  check this.

**Comment by Surajbokde** [comment]
![image](https://user-images.githubusercontent.com/66197682/98070832-e832e580-1e87-11eb-8dbf-fee242077b49.png)
see this i got ,we can do this by using container.
and after 2-3 sec the image get changed.

**Comment by Surajbokde** [comment]
![Uploading image.png…]()

**Comment by Surajbokde** [comment]
![image](https://user-images.githubusercontent.com/66197682/98071204-ef0e2800-1e88-11eb-8ed9-ece8e46aa81b.png)

**Comment by chehak123** [comment]
The first one is looking good.
Make a section in blog page and add this section and for now use any sample img and make a pr. Do add screenshots also.

**Comment by Harshita248** [comment]
done
