### ISSUE TITLE
Modify and create a blog page with certain blogs related to orphan support .

### ISSUE THREAD

**Issue by Harshita248** [sanscript-tech/orphan_support-php#46]
The details of writer should include name , mail and unique id . Data to be stored as well as fetched from database.

**Comment by pwilson77** [comment]
I will like to work on this issue @Harshita248

**Comment by Harshita248** [comment]
If you are enrolled as a participant under Autumn of Open Source 2020 then surely you can go ahead @pwilson77 otherwise don't

**Comment by chehak123** [comment]
@pwilson77 I have verified you as a participant in AOS so you can go ahead with this issue.

**Comment by pwilson77** [comment]
Sure @chehak123

**Comment by chehak123** [comment]
@pwilson77 complete it by today or it will be unassigned

**Comment by pwilson77** [comment]
@chehak123  can u unassign me I unfortunately I am busy all weekend

**Comment by chehak123** [comment]
okay @pwilson77

**Comment by Surajbokde** [comment]
@Harshita248 @chehak123 i would like to work on this issue . I will try to submit it till Monday night .

**Comment by Harshita248** [comment]
okay @Surajbokde

**Comment by Harshita248** [comment]
Try to submit till sunday if possible, we dont have much time

**Comment by Surajbokde** [comment]
@Harshita248  i make a pull request.

**Comment by Harshita248** [comment]
done nice work @Surajbokde
