### ISSUE TITLE
Please check the paths of the css , img and js folders before running the sample files

### ISSUE THREAD

**Issue by Harshita248** [sanscript-tech/orphan_support-php#5]
If the paths are not correct fix it and do a pr

**Comment by sravani-7701** [comment]
Would you please assign this to me

**Comment by ShauryaBhandari** [comment]
Assigned to you @sravani-7701 , please add the steps to run it in the readme as well, if needed.

**Comment by Adithya-adi-Menon** [comment]
Could You Please Assign this to me

**Comment by ShauryaBhandari** [comment]
@Adithya-adi-Menon There is an active PR for this issue, in case that is not merged, I will assign it to you.

**Comment by Adithya-adi-Menon** [comment]
I have successfully completed the issue . I kindly request you to review and merge the pull request

**Comment by Harshita248** [comment]
_For now I'm merging the pull request but unless you are assigned to work on a particular issue please don't make a pr otherwise it won't be merged._ @Adithya-adi-Menon

**Comment by Harshita248** [comment]
this has been done
