### ISSUE TITLE
Maintain a proper folder structure for keeping all the files in a structured manner.

### ISSUE THREAD

**Issue by Harshita248** [sanscript-tech/orphan_support-php#57]
Keep index.html and other related pages which we are using and remove the unnecessary ones like index-1 index-2 . Also once assigned for this issue , you will have 24 hours to complete it.

**Comment by bhavesh1129** [comment]
Hey! May I work on this?

**Comment by m-code12** [comment]
I would like to take this up.

**Comment by ankita413** [comment]
hey may i work on this?

**Comment by Harshita248** [comment]
@bhavesh1129 go ahead and complete it by today I need this as early as possible.
