### ISSUE TITLE
Add images to the readme wherever its missing and make it a little more descriptive .

### ISSUE THREAD

**Issue by Harshita248** [sanscript-tech/orphan_support-php#58]
There are some images for fork , clone etc missing so please add particular image at the appropriate place.

**Comment by bhavesh1129** [comment]
Hey! Can I take this up??

**Comment by m-code12** [comment]
I would like to take up this issue.

**Comment by Harshita248** [comment]
@m-code12  go ahead for this issue 
@bhavesh1129  you are already assigned with another one so work on that
