### ISSUE TITLE
Create proper folder structure

### ISSUE THREAD

**Issue by ShauryaBhandari** [sanscript-tech/orphan_support-php#6]
A proper and optimised folder structure needs to be created. I was thinking of a server-client classic folder structure, but it is open for discussion. 
Please discuss in this comment thread what you think might be the best option.

**Comment by sanchibansal340** [comment]
Server Client sounds good. We can move the assets folder inside the client.

**Comment by sravani-7701** [comment]
Server client idea is cool

**Comment by ShauryaBhandari** [comment]
Cool. I have started making issues, I will be adding more and also labels for the same as soon as I get write access to the repo. 
This issue can be taken up till then. :+1:

**Comment by sanchibansal340** [comment]
Would like to work on it.

**Comment by sanchibansal340** [comment]
@ShauryaBhandari There isn't any server side code for PHP from what I understand. 
I am not sure as I don't work with PHP but I guess there won't be any server side code either.

**Comment by ShauryaBhandari** [comment]
I see @sanchibansal340 . I have never worked with php till date, I would love to know more about the same. :D

**Comment by sanchibansal340** [comment]
@ShauryaBhandari Same, I work with Node.js
But after researching a bit I got to know that with PHP we make one .php file and include html code there itself.
We can run that PHP file using Xampp, Mamp

**Comment by Harshita248** [comment]
yeah you can go forward with this @sanchibansal340  it works the same as you told
