### ISSUE TITLE
Add a relatable header picture on blog page 

### ISSUE THREAD

**Issue by chehak123** [sanscript-tech/orphan_support-php#67]

**Comment by Surajbokde** [comment]
![image](https://user-images.githubusercontent.com/66197682/98442102-affe0200-2128-11eb-879b-ba2c8ec19118.png)
i choose this image

**Comment by bhavesh1129** [comment]
Can I take this up?

**Comment by Harshita248** [comment]
This is already done so should I'm closing this issue.
