### ISSUE TITLE
Update the logo and title on tab bar.

### ISSUE THREAD

**Issue by chehak123** [sanscript-tech/orphan_support-php#68]

**Comment by bhavesh1129** [comment]
Can you please explain a Lil more and then assign it to me?

**Comment by chehak123** [comment]
![Screenshot (364)_LI](https://user-images.githubusercontent.com/53402167/98460442-87c6df80-21ca-11eb-98da-a3be984821c8.jpg)

Change the logo and title (on navbar) on all the pages.

**Comment by Surajbokde** [comment]
@chehak123  i did the logo part in my resent pr . @bhavesh1129 just do the title part, and do it fast.

**Comment by ManasSahni** [comment]
Can I work on this?
