### ISSUE TITLE
Create a really good content for home and about us page maybe on google docs .

### ISSUE THREAD

**Issue by Harshita248** [sanscript-tech/orphan_support-php#69]
Share the link of google docs here , write content on it whenever you are working so that we can also have a look and lastly update it on home and about us page. No need for screenshots. Just provide google doc link where you will be writing the content.

**Comment by sakshi300699** [comment]
Would like to work on this

**Comment by Harshita248** [comment]
Sure go ahead and also provide the link of Google docs

**Comment by sakshi300699** [comment]
Okay Ma'am

**Comment by ineffable23** [comment]
I'm interested to work on it

**Comment by Harshita248** [comment]
You guyz maintain a Google docs and decide yourself which content is good for home page and about page and then put it in the Website. If you see a dummy content anywhere in the Website add the contents there and change it. @ineffable23 and @sakshi300699

**Comment by sakshi300699** [comment]
Okay Ma'am!

**Comment by ineffable23** [comment]
Okay ma'am 🙂

**Comment by sakshi300699** [comment]
LINK FOR GOOGLE DOCS - https://docs.google.com/document/d/18FyKd4UeROlRHQ2fQDgcHLi6RWKKyoZUrrXq-ODxUyQ/edit?usp=sharing
