### ISSUE TITLE
Orphan Support Logo

### ISSUE THREAD

**Issue by ShauryaBhandari** [sanscript-tech/orphan_support-php#7]
- A logo needs to be created for the project. Make sure it is available as a png, svg and .iso format. 
- Also, 1 for light mode and another for dark mode. 
- Multiple people can take this issue up, the best one shall be used. 
All the best, happy hacking!

**Comment by SanjeebNath382** [comment]
hey can i try this?

**Comment by ShauryaBhandari** [comment]
Please go ahead.

**Comment by punitsakre23** [comment]
Hi, I'll make one.

**Comment by Harshita248** [comment]
you also go ahead @punitsakre23  - the one which is found better will be used

**Comment by raksha27yadav** [comment]
can i take up the work?

**Comment by Harshita248** [comment]
Check the rules please. It's already assigned to two people . If not found good you can go ahead but not now. @raksha27yadav 
if you want to show you can on the slack channel

**Comment by raksha27yadav** [comment]
fine

**Comment by SanjeebNath382** [comment]
@ShauryaBhandari 
Logo 1- black
![logo2-black](https://user-images.githubusercontent.com/59302663/96541083-ddd7ef80-12bc-11eb-8e7e-ecaf30d9efc7.png)



Logo 2-black

![logo1-black](https://user-images.githubusercontent.com/59302663/96541312-5b036480-12bd-11eb-9453-9f7c592f0de7.png)

Please review these logos, i have them in white coloue as well for the dark mode.

**Comment by ShauryaBhandari** [comment]
Looks nice @SanjeebNath382 
@Harshita248 please review. Do we need to have orphan support in name or just sanscript?

**Comment by Harshita248** [comment]
Yes it looks good but if you have a word related to orphan instead of sanscript that would be much better . @SanjeebNath382 @ShauryaBhandari

**Comment by Shivangi22Agarwal** [comment]
Willing to try my graphic designing skills on this

**Comment by Harshita248** [comment]
Okay if you have made logos previously you can work on this @Shivangi22Agarwal

**Comment by Shivangi22Agarwal** [comment]
Thanks @Harshita248, if there's any preferences for color combination please let me know

**Comment by chehak123** [comment]
@Shivangi22Agarwal You can go ahead with black and white color scheme for now. Color scheme can be changed later on as per the website.

**Comment by bhavesh1129** [comment]
May I also try to design the logo?

**Comment by bhavesh1129** [comment]
@ShauryaBhandari, @Harshita248 
**LOGO-1(White)**

![OrphanWhiteLogo (1)](https://user-images.githubusercontent.com/54619203/96833191-a48ab580-145d-11eb-8891-c6a0a5a3fb72.png)

**LOGO-2(White)**

![OrpahnWhiteLogo2](https://user-images.githubusercontent.com/54619203/96834936-72c71e00-1460-11eb-90be-415ad7b62a6e.png)

Please review these logos, I've these logo's in black colour as well for the normal mode.

**Comment by Harshita248** [comment]
@bhavesh1129 please follow the rules and don't make a pr until you are assigned with it. For now I have merged the pr but please abide by the rules . Everyone will get a chance to work on it.

**Comment by bhavesh1129** [comment]
> @bhavesh1129 please follow the rules and don't make a pr until you are assigned with it. For now, I have merged the pr but please abide by the rules. Everyone will get a chance to work on it.

Oops Sorry, Harshita will take care of from next time.
and Thanks for merging my PR!!

**Comment by Surajbokde** [comment]
hey i design a logo ,so can i share?

**Comment by Harshita248** [comment]
@Surajbokde please share it on slack channel of orphan support php

**Comment by chehak123** [comment]
@SanjeebNath382 kindly add 1st logo suggested by you in the project and make the pr. Do add the screenshots along with it.

**Comment by chehak123** [comment]
@SanjeebNath382 make it fast or it will be assigned to someone else. Complete it by tomorrow.

**Comment by chehak123** [comment]
@Surajbokde do add your suggested logo in the project and make the pr by today itself. Do add the screenshots.

**Comment by Surajbokde** [comment]
@chehak123 thanks for assigning to me.
i will do it by today itself .
