### ISSUE TITLE
Work on contact us page and create a report section inside it.

### ISSUE THREAD

**Issue by Harshita248** [sanscript-tech/orphan_support-php#70]

**Comment by Surajbokde** [comment]
i would like to work on this

**Comment by Harshita248** [comment]
If a person finds a child or any elderly person abandoned by family ..one can create a report so that an email with the person's details and also the details of one who is abandoned should be sent to nearby orphanages. `Also add age limit and occupation +salary of a person who is creating the report`.

**Comment by Harshita248** [comment]
done
