### ISSUE TITLE
Remove the shopping cart icon on navbar and remove the header top on all pages which shows the social media icons and other details.

### ISSUE THREAD

**Issue by chehak123** [sanscript-tech/orphan_support-php#73]

**Comment by m-code12** [comment]
I would like to take this up

**Comment by chehak123** [comment]
Go ahead @m-code12

**Comment by Surajbokde** [comment]
@m-code12 do it by today plz.

**Comment by Surajbokde** [comment]
@chehak123 is there any need to remove header top which include social media icons.???
i don't think so coz when we scroll down it will hide.

**Comment by m-code12** [comment]
> @m-code12 do it by today plz.

Yes, I will make a pr by today

**Comment by Harshita248** [comment]
done
