### ISSUE TITLE
Improve Documentation 

### ISSUE THREAD

**Issue by ShauryaBhandari** [sanscript-tech/orphan_support-php#8]
- There are a lot of grammatical errors in the README, that needs to be changed. 
- Add more details about the project. 
- Add gifs, images, etc. to make it more readable and attractive. 
**All the best!**

**Comment by odavhad** [comment]
May I work on this?

**Comment by ghost** [comment]
May I work on this?

**Comment by sakshi300699** [comment]
Can I give a hand too if possible?

**Comment by SanjeebNath382** [comment]
can i work on this?

**Comment by ShauryaBhandari** [comment]
Only 2 people can be assigned an issue at a time, so I am assigning @sakshi300699 
If they fail to complete it, I will assign it to you @SanjeebNath382

**Comment by shivangisinghal0304** [comment]
Can I work on this?

**Comment by Harshita248** [comment]
This issue has been completed by @sakshi300699
