### ISSUE TITLE
Overall Design

### ISSUE THREAD

**Issue by ShauryaBhandari** [sanscript-tech/orphan_support-php#9]
**NOTE: THIS IS NOT AN ISSUE**
This is just a discussion thread to discuss the design we can go ahead with for the project. Example templates/mockups are welcome.
I would like to keep the design minimalistic and clean, discussions welcome. 
Also, it should have a dark/light mode. 
Please comment any suggestions you might have.

**Comment by Git-Harshit** [comment]
Checking up the current page design and progress after every update manually is redundant, and we can instead rely on a live demo of the main branch. It'd be great if the sanscript-tech team could host their repository online (even with GitHub-Pages should work).

**Comment by Yashi30** [comment]
https://colorlib.com/wp/template/unicare/
Can use this template for Landing page!!

**Comment by ShauryaBhandari** [comment]
Makes sense @Git-Harshit 
@Harshita248  Please look into this once.

**Comment by akshat-fsociety** [comment]
@ShauryaBhandari template for design idea
![Screenshot (63)](https://user-images.githubusercontent.com/64137417/96400978-ced73b80-11ef-11eb-8f04-609f52d6ec96.png)

**Comment by Harshita248** [comment]
For that @Git-Harshit I need to talk to them . Will let you know : )   And @akshat-fsociety the template looks good . When few people will put their templates idea , we will decide which one to go with after a discussion with everyone.

**Comment by bhavesh1129** [comment]
May I work on it?

**Comment by ShauryaBhandari** [comment]
Go on @bhavesh1129 , we would like to have as many options as possible.

**Comment by debargham14** [comment]
For this project we can consider two things important 1. the schema of the project (main functionalities and their flow) 2. the template (bootstrap files that we'll be working on). For bootstrap we can use md boot strap its good and easy to use
@ShauryaBhandari

**Comment by ShauryaBhandari** [comment]
Right on point @debargham14 , we have to finalize the template by today and start working on the schema and flow from tomorrow.

**Comment by Shivangi22Agarwal** [comment]
I'd love to design nice graphics ( using colors as per the demand ) for the website

**Comment by chehak123** [comment]
@Shivangi22Agarwal you can put forward your ideas regarding it.

**Comment by Harshita248** [comment]
@akshat-fsociety please send the link of the screenshot of the template that you have mentioned above. We want to see as we are looking for a good one .

**Comment by akshat-fsociety** [comment]
@Harshita248 https://www.operation-orphan.org/

**Comment by Harshita248** [comment]
this is done
